### ISSUE TITLE
Group Necessary Configuration Items on Config & Resets Page

### ISSUE THREAD

**Issue by kylekrieg** [kylekrieg/Node-Red-Contesting-Dashboard#26]
Users are not knowing what configuration items they need to set and which ones they don't.  We should look at grouping all the necessary configuration parameters someone needs to set in one dashboard group to get the contest up and running.  Everything else would be optional.

**Comment by kd9lsv** [comment]
@kylekrieg 
Or do we denote all the major fields with a `*` or a designation meaning they are major fills.

**Comment by kylekrieg** [comment]
We can, but those * will be all over the place.  I wonder if we can somehow group them but also keep them together.  NR is not the best in placing dashboard groups together and keeping them together.  I'm assuming when they move from this dashboard setup to their new setup (which is coming) moving groups and dashboard nodes within groups will be much easier.
