### ISSUE TITLE
Display Logged Q on Dashboard (beside & above map) even if Q is not found in QRZ/HamQTH or HamDB.

### ISSUE THREAD

**Issue by kylekrieg** [kylekrieg/Node-Red-Contesting-Dashboard#39]
Today if the Q is not found in one of the 3 lookup databases, it does not display on the homepage.

Maybe diverge the map info from the database front page display nodes and allow the Q to display to the dashboard and then look the contact up on the map?

**Comment by kd9lsv** [comment]
Added in #43
