### ISSUE TITLE
HAMQTH

### ISSUE THREAD

**Issue by s53zo** [kylekrieg/Node-Red-Contesting-Dashboard#4]
Can you please include www.hamqth.com, has far more data than hamdb and it is free...

73 & TNX

**Comment by kylekrieg** [comment]
Thanks for the idea and suggestion. I had no idea it was free.  I'm currently in the process of making this an option.  I should have a new version out by the end of the week.  73  Kyle

**Comment by kylekrieg** [comment]
Resolved.  New version released.
