### ISSUE TITLE
[Bug]: TTL in Map Configuration 

### ISSUE THREAD

**Issue by JackHenry99** [kylekrieg/Node-Red-Contesting-Dashboard#47]
### Contact Details

john@tudorfarm.net.au

### What happened?

Upgraded to 1.2.18

There seems to be no 'Submit' button for the Map Configuration TTL. Thinking that maybe it just takes a change without the need to 'Submit' it, I changed it to 30 seconds. After going into the dashboard and back to the configuration page, it had defaulted back to 1200

Regards
John VK5JAK

### Version

1.2.18

### Environment

```markdown
- **OS** : Pi Bullseye 5.15.84-v7l+
- **Node.js** : v19.2.0
```

### What browsers are you seeing the problem on?

Firefox, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kd9lsv** [comment]
@JackHenry99  Fix is incoming when @kylekrieg  approve changes.
