### ISSUE TITLE
Issue with Distance and Exchange

### ISSUE THREAD

**Issue by GregTroar** [kylekrieg/Node-Red-Contesting-Dashboard#5]
Hello,

I have put my login and password for QRZ.com lookup but still I always have a NaN for the distance while it is working well with HamQTH.

Exchange is not appearing as well.

I have tested with contest CQ WPX SSB.

Any hint to resolve the NaN issue ?
How can I debug ?

Thanks
Greg

**Comment by GregTroar** [comment]
exchange is solved, did not put the proper exchange type in setup.
Still an issue qith qrz.com though

**Comment by kylekrieg** [comment]
I just tested this and it's working on my end.

A few things you might want to check.

1) You need a QRZ XML lookup subscription to look up locations.  If you
don't have that subscription, it will not work.

2) Your lat/lon needs to be entered correctly.

3) I have seen where the first lookup fails to be displayed on the map, but
sequential lookups do get displayed.

Thanks
Kyle
