### ISSUE TITLE
Ability to Control Temperature conversion.

### ISSUE THREAD

**Issue by kd9lsv** [kylekrieg/Node-Red-Contesting-Dashboard#50]
### The feature request

Allow for the ability to control the temperature units in the config page.

### Proposed solution

Create a Dropdown with the options to set a global variable that is read to set the output to proper value and units.

### Pages Impacted

Pi Status, Configuration & Resets

### Submission

- [X] I agree this is the first post associated with this feature.

**Comment by KK1L** [comment]
I added that to my version a while ago. If i can figure out how to push it to y'all I can do that.73 es God Bless de KK1L, Ron <><On Jan 18, 2023 23:21, Connor Dickey ***@***.***> wrote:
The feature request
Allow for the ability to control the temperature units in the config page.
Proposed solution
Create a Dropdown with the options to set a global variable that is read to set the output to proper value and units.
Pages Impacted
Pi Status, Configuration & Resets
Additional context
No response
Submission
 I agree this is the first post associated with this feature.

**Comment by kd9lsv** [comment]
1. Fork the project  ( Google is your friend there) 
     
    
      2. Create a branch that has the changes ( label it like issue-50) 
     
    
      3. Create a Pull Request with the changes to point to branch dev. KyleKrieg\Dev < KK1L\Issue-50 
     
     
      
     
    
      Hope that helps. 
     
    
      73, 
     
    
      Connor KD9LSV  
     
     
      
     
    
    
     
      
       
      
     
    
    
    
     
     
       On Wednesday, Jan 18, 2023 at 11:23 PM, Ron Rossi ***@***.***> wrote: 
       
      
      
      I added that to my version a while ago. If i can figure out how to push it to y'all I can do that.73 es God Bless de KK1L, Ron <><On Jan 18, 2023 23:21, Connor Dickey ***@***.***> wrote: 
      The feature request 
      Allow for the ability to control the temperature units in the config page. 
      Proposed solution 
      Create a Dropdown with the options to set a global variable that is read to set the output to proper value and units. 
      Pages Impacted 
      Pi Status, Configuration & Resets 
      Additional context 
      No response 
      Submission 
       I agree this is the first post associated with this feature. 
       
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/kylekrieg/Node-Red-Contesting-Dashboard/issues/50#issuecomment-1396455484","url": "https://github.com/kylekrieg/Node-Red-Contesting-Dashboard/issues/50#issuecomment-1396455484","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]
