### ISSUE TITLE
[Bug]:?? Home Lat Lon Submit Button 

### ISSUE THREAD

**Issue by JackHenry99** [kylekrieg/Node-Red-Contesting-Dashboard#52]
### Contact Details

john@tudorfarm.net.au

### What happened?

1.2.20 on MacBook & Firefox plus Windows & Firefox.

Configuration page. Home Submit Button only seems to work on the very top edge of the button. Other Submit buttons work for entire button surface.

Regards
John VK5JAK

### Version

1.2.20

### Environment

```markdown
- **OS** : Mac 10.15.7 & Windows 10 
- **Node.js** : 19.2.0
```

### What browsers are you seeing the problem on?

Firefox, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kd9lsv** [comment]
@JackHenry99 I can confirm this is valid. I'm just trying to find the best way to implement the fix.

**Comment by kd9lsv** [comment]
@JackHenry99  Fixed is pushed to dev branch.
