### ISSUE TITLE
[Bug]: Radio names not working

### ISSUE THREAD

**Issue by Vulp35** [kylekrieg/Node-Red-Contesting-Dashboard#61]
### What happened?

No radio data showing on main dashboard. No computer names showing under "Radio Names" in configuration. Manual computer name entry will let me set a computer name to a radio, but still does not show any radio information on dashboards.

### Version

1.2.20

### Environment

```markdown
- **OS** : Armbian Bullseye (Inovato Quadra)
- **Node.js** : 16.19.1
```

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output

```shell
3/26/2023, 2:50:27 PMnode: Add Placeholders and Options
function : (warn)
"{"StationName":"RUSS-LENOVO"}"
3/26/2023, 2:50:27 PMnode: Add Placeholders and Options
function : (warn)
"RUSS-LENOVO"
3/26/2023, 2:50:28 PMnode: Add Placeholders and Options
function : (warn)
[ "RUSS-LENOVO" ]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kd9lsv** [comment]
Just want to make sure, that you've also configured N1MM to point to the Node Red install.

https://github.com/kylekrieg/Node-Red-Contesting-Dashboard/blob/master/INSTALL.md

If that is completed does the issue part of #59 include this?

**Comment by Vulp35** [comment]
I do! The contacts and everything else seem to be working. I'm not sure if the issue referenced includes this or not.

<img width="548" alt="Screenshot 2023-03-26 180032" src="https://user-images.githubusercontent.com/45741898/227810489-31fa2e43-f8fa-41b9-bb87-8b8c23365cc3.png">
<img width="744" alt="Screenshot 2023-03-26 180433" src="https://user-images.githubusercontent.com/45741898/227810488-4971c78c-3e9e-4206-8370-10536adaf1bf.png">

Going into the Dashboard Flow and looking at `Radio Data Raw` debug node I get this output:
```JSON
{
  "RadioInfo": {
    "app": ["N1MM"],
    "StationName": ["RUSS-LENOVO"],
    "RadioNr": ["1"],
    "Freq": ["1424500"],
    "TXFreq": ["1424500"],
    "Mode": ["USB"],
    "OpCall": ["KF0JOU"],
    ...
  }
}
```

This is what my dashboard shows, and how configuration looks for the radios. (Note: the computer name was added manually.)

<img width="1280" alt="Screenshot 2023-03-26 181111" src="https://user-images.githubusercontent.com/45741898/227811080-259c2589-43f4-425a-90f5-71b6d70b85fd.png">
<img width="143" alt="Screenshot 2023-03-26 181836" src="https://user-images.githubusercontent.com/45741898/227811085-4ecb586d-a713-4dbe-96e6-13b3a42e2887.png">

**Comment by kd9lsv** [comment]
I believe so. It has been a while since I've actually had a time and effort to put into this.

@kk1l is this the same thing that was wrong Ron?

**Comment by KK1L** [comment]
Yes. The computer name does not come from the "Radio Names". It is the Station Name from N1MM+, but they are hardcoded to Radio1, 2, 3, etc as the Group Name in the dashboards. I have a version which uses the name assigned in the Config page, but there is something in the flow which causes excessive CPU usage. I have not had the oportunity to spend time on the flow in well over a month now.

**Comment by kd9lsv** [comment]
Going to close due to matching with #59
