### ISSUE TITLE
Worldmap center

### ISSUE THREAD

**Issue by s53zo** [kylekrieg/Node-Red-Contesting-Dashboard#8]
Please use coordinates (LAT/LON) given in the configure tab as a home location on the world map. Now it is defaulted to somewhere in USA.

**Comment by kylekrieg** [comment]
I put a button in the upper left hand to center the map.  It should now center on the lat/lon that's entered into the config screens with a zoom level of 4.

**Comment by kylekrieg** [comment]
Connor @kd9lsv fixed this.  Closing this issue.
